api:
    entity_aliases:
        Oro\Bundle\OrganizationBundle\Api\Model\Contact:
            alias: suggestorganization
            plural_alias: suggestorganization
        Oro\Bundle\OrganizationBundle\Api\Model\SearchByPhone:
            alias: searchorganizationbyphone
            plural_alias: searchorganizationbyphone
    entities:
        Oro\Bundle\OrganizationBundle\Entity\BusinessUnit:
            documentation_resource: '@OroOrganizationBundle/Resources/doc/api/business_unit.md'
            actions:
                delete:
                    exclude: false # set manually because this entity is marked as a dictionary
                delete_list:
                    exclude: false # set manually because this entity is marked as a dictionary
                create:
                    exclude: false # set manually because this entity is marked as a dictionary
                update:
                    exclude: false # set manually because this entity is marked as a dictionary

        Oro\Bundle\OrganizationBundle\Entity\Organization:
            documentation_resource: '@OroOrganizationBundle/Resources/doc/api/organization.md'
            fields:
                skip_acl_for_root_entity: true
                businessUnits:
                    form_options:
                        mapped: false
                users:
                    form_options:
                        mapped: false

                linkCustomersOrganizations:
                    form_options:
                        mapped: false
            filters:
                fields:
                    name:
                        operators: ['=', '!=', '*', '!*', '~', '!~', '^', '!^', '$', '!$']
                    phone: 
                        operators: ['=', '!=', '*', '!*', '~', '!~', '^', '!^', '$', '!$']
                    countryCode:
                        operators: ['=', '!=', '*', '!*', '~', '!~', '^', '!^', '$', '!$']
                    linkCustomersOrganizations:
                        exclude: false
            actions:
                delete: false
                delete_list: false
                create: true

        Oro\Bundle\OrganizationBundle\Api\Model\Contact:
            documentation_resource: '@OroOrganizationBundle/Resources/doc/api/suggest_organizations.md'
            fields:
                lstPhone:
                    data_type: string
                data:
                    data_type: array
            actions:
                get: false
                get_list: false
                create:
                    description: Get API Access Key
                    fields:
                        lstPhone:
                            direction: input-only
                        data:
                            direction: output-only
                    status_codes:
                        201: false
                        200: Returned when the credentials are valid and API access key exists
                        403: Returned when the credentials are not valid or API access key does not exist
                        409: false

        Oro\Bundle\OrganizationBundle\Api\Model\SearchByPhone:
            documentation_resource: '@OroOrganizationBundle/Resources/doc/api/search_organizations.md'
            fields:
                phone:
                    data_type: string
                countryCode:
                    data_type: string
                data:
                    data_type: array
            actions:
                get: false
                get_list: false
                create:
                    description: Get API Access Key
                    fields:
                        phone:
                            direction: input-only
                        countryCode:
                            direction: input-only
                        data:
                            direction: output-only
                    status_codes:
                        201: false
                        200: Returned when the credentials are valid and API access key exists
                        403: Returned when the credentials are not valid or API access key does not exist
                        409: false