security:
    firewalls:
        frontend_api_options:
            pattern: '%oro_api.rest.pattern%'
            methods: [OPTIONS]
            security: false

        frontend_api_create_organization:
            pattern: '^/admin/api/organizations'
            anonymous: true
            stateless: true
       
        frontend_api_searchorganization:
            pattern: '^%oro_api.rest.prefix%searchorganization'
            security: false
            stateless: true
      

